[project]
name = "game-sale-rec-proj"
version = "0.1.0"
description = ""
authors = [
    {name = "Jeremy Tu",email = "dipper.lynx9827@eagereverest.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas (>=2.3.3,<3.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "requests (>=2.32.5,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
]

[tool.poetry]
package-mode = false
packages = [{include = "game_sale_rec_proj", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.0.1,<8.0.0)"
]
